# FORMAT LEGEND:
# [ASSET] -> backgrounds, sprites, transitions, CG/UI callouts
# [STATE] -> variable changes, effects, conditions, jumps
# [CHOICE] -> menu blocks and inflection points
# [BEAT] -> narrative intent / scene intent notes
#
# SPRITE DIRECTION (managed by scripts/scene_direction.py — how to preserve manual staging):
# [asset auto]              -> auto-placed sprite line; the agent may rewrite/replace it on re-run
# [asset keep]              -> on a show line: lock THAT line so the agent never edits it
# [asset lock:scene]        -> before/after a `scene`: the agent skips the entire scene block
# [asset pin:Name=slot]     -> force Name into slot for the rest of the scene block
# [enter:Name] / [exit:Name] -> declare cast changes so auto placement stays correct
# Full policy: docs/contracts/sprite_layout_policy.yaml | spec: docs/specs/scene-direction-agent.md

# Generated by scripts/generate_balance_profiles_rpy.py — do not edit by hand.
# Source: main-game/draft/releases/planning/balance/effect_profiles.yaml

init -1 python in balance_resolver:

    BALANCE_STAT_UNITS = {"insp": 50, "corr": 20, "susp": 100}

    BALANCE_INTENSITIES = {"trace": 0.05, "minor": 0.1, "standard": 0.25, "major": 0.4, "severe": 0.6}

    BALANCE_VALID_WITNESSES = ("stern", "vance", "gideon", "missy")

    BALANCE_PROFILES = {
        "safe": {"insp": "trace"},
        "observant": {"insp": "minor"},
        "curious": {"insp": "standard", "corr": "minor"},
        "obedient": {"corr": "minor", "insp": "trace"},
        "submissive": {"corr": "standard", "insp": "minor"},
        "defiant": {"insp": "standard", "witness_susp": "minor"},
        "deceptive": {"insp": "minor", "witness_susp": "standard"},
        "transgressive": {"corr": "standard", "insp": "standard"},
        "reckless": {"corr": "major", "insp": "standard", "witness_susp": "standard"},
        "predatory": {"corr": "major", "insp": "minor", "witness_susp": "minor"},
        "self_protective": {"insp": "minor"},
        "creative": {"insp": "standard"},
    }

    SCALE_PRECISION = 6

    def _is_number(value):
        return isinstance(value, (int, float)) and not isinstance(value, bool)

    def _clean_scale(value):
        return round(float(value), SCALE_PRECISION)

    def _resolve_balance_amount(stat_key, intensity_key, scale_modifier=1.0):
        if intensity_key is None:
            return 0

        if stat_key not in BALANCE_STAT_UNITS:
            raise ValueError("Unknown balance stat unit: {}".format(stat_key))

        scale_modifier = _clean_scale(scale_modifier)
        base_unit = BALANCE_STAT_UNITS[stat_key]

        if _is_number(intensity_key):
            base_multiplier = _clean_scale(intensity_key)
        else:
            if intensity_key not in BALANCE_INTENSITIES:
                raise ValueError("Unknown balance intensity constant: {}".format(intensity_key))
            base_multiplier = _clean_scale(BALANCE_INTENSITIES[intensity_key])

        return int(round(base_unit * base_multiplier * scale_modifier))

    def _resolve_intensity_scale_modifier(intensity_override):
        if intensity_override is None or intensity_override == "standard":
            return 1.0

        if _is_number(intensity_override):
            return _clean_scale(intensity_override)

        if intensity_override not in BALANCE_INTENSITIES:
            raise ValueError("Unknown balance intensity override: {}".format(intensity_override))

        standard = BALANCE_INTENSITIES["standard"]
        if standard == 0:
            raise ValueError("BALANCE_INTENSITIES['standard'] cannot be zero.")

        return _clean_scale(BALANCE_INTENSITIES[intensity_override] / standard)

    def resolve_balanced_effect(profile, intensity_override=None, witness=None, base_witness=False):
        if profile not in BALANCE_PROFILES:
            raise ValueError("Unknown balance profile: {}".format(profile))

        if witness is not None and witness not in BALANCE_VALID_WITNESSES:
            raise ValueError(
                "Unknown witness '{}'. Must be one of: {}".format(
                    witness,
                    ", ".join(BALANCE_VALID_WITNESSES),
                )
            )

        spec = BALANCE_PROFILES[profile]
        kwargs = {}
        scale_mod = _resolve_intensity_scale_modifier(intensity_override)

        if "insp" in spec:
            kwargs["insp"] = _resolve_balance_amount("insp", spec["insp"], scale_mod)

        if "corr" in spec:
            kwargs["corr"] = _resolve_balance_amount("corr", spec["corr"], scale_mod)

        if "witness_susp" in spec:
            if witness is None:
                raise ValueError("Profile '{}' requires a named witness parameter.".format(profile))

            amount = _resolve_balance_amount("susp", spec["witness_susp"], scale_mod)
            key = "{}_base".format(witness) if base_witness else "{}_susp".format(witness)
            kwargs[key] = amount

        return kwargs

