# FORMAT LEGEND:
# [ASSET] -> backgrounds, sprites, transitions, CG/UI callouts
# [STATE] -> variable changes, effects, conditions, jumps
# [CHOICE] -> menu blocks and inflection points
# [BEAT] -> narrative intent / scene intent notes
#
# SPRITE DIRECTION (managed by scripts/scene_direction.py — how to preserve manual staging):
# [asset auto]              -> auto-placed sprite line; the agent may rewrite/replace it on re-run
# [asset keep]              -> on a show line: lock THAT line so the agent never edits it
# [asset lock:scene]        -> before/after a `scene`: the agent skips the entire scene block
# [asset pin:Name=slot]     -> force Name into slot for the rest of the scene block
# [enter:Name] / [exit:Name] -> declare cast changes so auto placement stays correct
# Full policy: docs/contracts/sprite_layout_policy.yaml | spec: docs/specs/scene-direction-agent.md

# Generated by scripts/generate_balance_profiles_rpy.py — do not edit by hand.
# Source: main-game/draft/releases/planning/balance/effect_profiles.yaml

init -1 python in balance_resolver:

    BALANCE_SCHEMA_VERSION = 2
    BALANCE_ACTIVE_INTENSITIES = ("minor", "standard", "major")
    BALANCE_MIGRATION_ALLOWED_STORY_INTENSITIES = ("standard")
    BALANCE_VALID_WITNESSES = ("stern", "vance", "gideon", "missy")

    BALANCE_PROFILES = {
        "creative": {
            "active": True,
        "deltas": {
            "minor": {'insp': 2, 'corr': 1, 'witness_susp': 0},
            "standard": {'insp': 5, 'corr': 3, 'witness_susp': 0},
            "major": {'insp': 12, 'corr': 6, 'witness_susp': 0},
        }
        },
        "curious": {
            "active": True,
        "deltas": {
            "minor": {'insp': 1, 'corr': 2, 'witness_susp': 5},
            "standard": {'insp': 3, 'corr': 6, 'witness_susp': 10},
            "major": {'insp': 6, 'corr': 12, 'witness_susp': 15},
        }
        },
        "transgressive": {
            "active": True,
        "deltas": {
            "minor": {'insp': 0, 'corr': 4, 'witness_susp': 10},
            "standard": {'insp': 0, 'corr': 10, 'witness_susp': 15},
            "major": {'insp': 0, 'corr': 24, 'witness_susp': 25},
        }
        },
        "observant": {
            "active": True,
        "deltas": {
            "minor": {'insp': 1, 'corr': 0, 'witness_susp': 0},
            "standard": {'insp': 2, 'corr': 0, 'witness_susp': 0},
            "major": {'insp': 5, 'corr': 0, 'witness_susp': 0},
        }
        },
        "deceptive": {
            "active": True,
        "deltas": {
            "minor": {'insp': 0, 'corr': 6, 'witness_susp': 5},
            "standard": {'insp': 0, 'corr': 8, 'witness_susp': 10},
            "major": {'insp': 0, 'corr': 20, 'witness_susp': 25},
        }
        },
        "safe": {
            "active": False,
        "migration_hint": "observant"
        },
        "obedient": {
            "active": False,
        "migration_hint": "observant_or_deceptive"
        },
        "submissive": {
            "active": False,
        "migration_hint": "curious_or_transgressive"
        },
        "defiant": {
            "active": False,
        "migration_hint": "observant_or_deceptive"
        },
        "reckless": {
            "active": False,
        "migration_hint": "transgressive_or_deceptive"
        },
        "predatory": {
            "active": False,
        "migration_hint": "transgressive"
        },
        "self_protective": {
            "active": False,
        "migration_hint": "observant"
        },
    }

    def resolve_balanced_effect(profile, intensity_override="standard", witness=None, base_witness=False):
        if profile not in BALANCE_PROFILES:
            raise ValueError("Unknown balance profile: {}".format(profile))

        prof_data = BALANCE_PROFILES[profile]
        if not prof_data.get("active", False):
            raise ValueError("Profile '{}' is inactive.".format(profile))

        intensity = intensity_override if intensity_override is not None else "standard"

        if isinstance(intensity, (int, float)) and not isinstance(intensity, bool):
            raise ValueError("Numeric intensity override not supported in schema v2: {}".format(intensity))

        if intensity not in BALANCE_ACTIVE_INTENSITIES:
            raise ValueError("Inactive or unknown intensity: {}".format(intensity))

        if base_witness:
            raise ValueError("base_witness=True is not allowed for active profiles during this migration pass.")

        deltas = prof_data.get("deltas", {}).get(intensity, {})

        kwargs = {}
        if deltas.get("insp", 0) != 0:
            kwargs["insp"] = deltas["insp"]
        if deltas.get("corr", 0) != 0:
            kwargs["corr"] = deltas["corr"]

        witness_susp = deltas.get("witness_susp", 0)
        if witness_susp != 0:
            if witness is None:
                raise ValueError("Profile '{}' requires a named witness parameter.".format(profile))
            if witness not in BALANCE_VALID_WITNESSES:
                raise ValueError("Unknown witness '{}'. Must be one of: {}".format(witness, ", ".join(BALANCE_VALID_WITNESSES)))
            key = "{}_base".format(witness) if base_witness else "{}_susp".format(witness)
            kwargs[key] = witness_susp

        return kwargs
