# Narrative Pressure UI, Objective Journal, and Manuscript Readiness System: Data Layer

# Static Library - defined since it is read-only template data
define material_library = {
    "mat_safe_chore_detail": {
        "id": "mat_safe_chore_detail",
        "chapter_id": "chapter_01",
        "assignment_id": "assignment_01",
        "value": 1,
        "tier": 1,
        "tags": ["mundane", "observation"],
        "journal_text": "Cora noted Lady Eleanor's nervous sorting of linen.",
        "expires_after_chapter": True,
        "consumed": False,
    },
    "mat_locked_room_glimpse": {
        "id": "mat_locked_room_glimpse",
        "chapter_id": "chapter_01",
        "assignment_id": "assignment_01",
        "value": 2,
        "tier": 2,
        "tags": ["scandal", "vance", "locked_room"],
        "journal_text": "Cora glimpsed a locked desk containing private correspondence.",
        "expires_after_chapter": True,
        "consumed": False,
    },
    "mat_vance_supper_secret": {
        "id": "mat_vance_supper_secret",
        "chapter_id": "chapter_01",
        "assignment_id": "assignment_01",
        "value": 2,
        "tier": 2,
        "tags": ["scandal", "vance"],
        "journal_text": "Cora overheard Vance discussing a midnight rendezvous.",
        "expires_after_chapter": True,
        "consumed": False,
    },
    "mat_gideon_blackmail_evidence": {
        "id": "mat_gideon_blackmail_evidence",
        "chapter_id": "chapter_01",
        "assignment_id": "assignment_01",
        "value": 3,
        "tier": 3,
        "tags": ["evidence", "blackmail"],
        "journal_text": "Cora secured a discarded note in Gideon's distinctive sloped hand.",
        "expires_after_chapter": True,
        "consumed": False,
    },
    "mat_prologue_letters": {
        "id": "mat_prologue_letters",
        "chapter_id": "prologue",
        "assignment_id": "prologue_assignment",
        "value": 3,
        "tier": 2,
        "tags": ["scandal", "letters"],
        "journal_text": "Cora read Lady Eleanor's private correspondence describing low, delicious agony in Margaret's hands.",
        "expires_after_chapter": True,
        "consumed": False,
    },
    "mat_prologue_encounter": {
        "id": "mat_prologue_encounter",
        "chapter_id": "prologue",
        "assignment_id": "prologue_assignment",
        "value": 3,
        "tier": 2,
        "tags": ["scandal", "encounter"],
        "journal_text": "Cora witnessed Lady Eleanor's intimate submission to under-housemaid Margaret.",
        "expires_after_chapter": True,
        "consumed": False,
    }
}
