flowchart TD
  day100_main["day100_main"] -->|"jump"| day100_1_afternoon_boredom_setup["day100_1_afternoon_boredom_setup"]
  day100_1_afternoon_boredom_setup["day100_1_afternoon_boredom_setup"] -->|"jump"| day100_1_afternoon_boredom["day100_1_afternoon_boredom"]
  day100_1_afternoon_boredom["day100_1_afternoon_boredom"] -->|"jump"| day100_2_desk_branch["day100_2_desk_branch"]
  day100_1_afternoon_boredom["day100_1_afternoon_boredom"] -->|"jump"| day100_2_parlour_branch["day100_2_parlour_branch"]
  day100_2_evening_flashback["day100_2_evening_flashback"] -->|"jump"| day100_2_desk_branch["day100_2_desk_branch"]
  day100_2_evening_flashback["day100_2_evening_flashback"] -->|"jump"| day100_2_parlour_branch["day100_2_parlour_branch"]
  day100_2_parlour_branch["day100_2_parlour_branch"] -->|"jump"| day100_2_reconvergence["day100_2_reconvergence"]
  day100_2_desk_branch["day100_2_desk_branch"] -->|"jump"| day100_2_reconvergence["day100_2_reconvergence"]
  day100_2_reconvergence["day100_2_reconvergence"] -->|"jump"| day100_3_night_daydream["day100_3_night_daydream"]
  day100_3_night_daydream["day100_3_night_daydream"] -->|"jump"| day100_3_arrival["day100_3_arrival"]
  day100_3_arrival["day100_3_arrival"] -->|"jump"| day101_main["day101_main"]
  day101_main["day101_main"] -->|"jump"| day101_1_cora_waiting["day101_1_cora_waiting"]
  day101_1_cora_waiting["day101_1_cora_waiting"] -->|"jump"| day101_1_morning_interview["day101_1_morning_interview"]
  day101_1_morning_interview["day101_1_morning_interview"] -->|"jump"| day101_1_vance_throws_toy["day101_1_vance_throws_toy"]
  day101_1_vance_throws_toy["day101_1_vance_throws_toy"] -->|"jump"| day101_1_vance_dressing_room["day101_1_vance_dressing_room"]
  day101_1_vance_dressing_room["day101_1_vance_dressing_room"] -->|"jump"| day101_1_vance_stairwell_encounter["day101_1_vance_stairwell_encounter"]
  day101_1_vance_stairwell_encounter["day101_1_vance_stairwell_encounter"] -->|"jump"| day101_2_missy_meets_cora["day101_2_missy_meets_cora"]
  day101_2_missy_meets_cora["day101_2_missy_meets_cora"] -->|"jump"| day101_2_coras_path_choice["day101_2_coras_path_choice"]
  day101_2_coras_path_choice["day101_2_coras_path_choice"] -->|"jump"| day101_3_taking_stock_day1["day101_3_taking_stock_day1"]
  day101_3_taking_stock_day1["day101_3_taking_stock_day1"] -->|"jump"| day102_1_cora_missy_first_shift["day102_1_cora_missy_first_shift"]
  day102_1_cora_missy_first_shift["day102_1_cora_missy_first_shift"] -->|"jump"| day102_1_missy_finds_a_thing["day102_1_missy_finds_a_thing"]
  day102_1_missy_finds_a_thing["day102_1_missy_finds_a_thing"] -->|"jump"| day102_1_cora_takes_the_thing["day102_1_cora_takes_the_thing"]
  day102_1_missy_finds_a_thing["day102_1_missy_finds_a_thing"] -->|"jump"| day102_1_cora_deceives_missy["day102_1_cora_deceives_missy"]
  day102_1_cora_takes_the_thing["day102_1_cora_takes_the_thing"] -->|"jump"| day102_2_day2_chore_time["day102_2_day2_chore_time"]
  day102_1_cora_deceives_missy["day102_1_cora_deceives_missy"] -->|"jump"| day102_2_day2_chore_time["day102_2_day2_chore_time"]
  day102_2_day2_chore_time["day102_2_day2_chore_time"] -->|"jump"| day102_2_day2_insp_choice["day102_2_day2_insp_choice"]
  day102_2_day2_chore_time["day102_2_day2_chore_time"] -->|"jump"| day102_2_day2_corr_choice["day102_2_day2_corr_choice"]
  day102_2_day2_insp_choice["day102_2_day2_insp_choice"] -->|"jump"| day102_3_stern_fetches_cora["day102_3_stern_fetches_cora"]
  day102_2_day2_corr_choice["day102_2_day2_corr_choice"] -->|"jump"| day102_3_stern_fetches_cora["day102_3_stern_fetches_cora"]
  day102_3_stern_fetches_cora["day102_3_stern_fetches_cora"] -->|"jump"| day102_3_vance_goes_incandescent["day102_3_vance_goes_incandescent"]
  day102_3_vance_goes_incandescent["day102_3_vance_goes_incandescent"] -->|"jump"| day102_3_coras_choice["day102_3_coras_choice"]
  day102_3_coras_choice["day102_3_coras_choice"] -->|"jump"| day102_3_cora_confesses["day102_3_cora_confesses"]
  day102_3_coras_choice["day102_3_coras_choice"] -->|"jump"| day102_3_cora_pretends_to_find_it["day102_3_cora_pretends_to_find_it"]
  day102_3_coras_choice["day102_3_coras_choice"] -->|"jump"| day102_3_cora_frames_missy["day102_3_cora_frames_missy"]
  day102_3_cora_confesses["day102_3_cora_confesses"] -->|"jump"| day102_3_gideon_interrupts_controls_vance["day102_3_gideon_interrupts_controls_vance"]
  day102_3_cora_pretends_to_find_it["day102_3_cora_pretends_to_find_it"] -->|"jump"| day102_3_gideon_interrupts_controls_vance["day102_3_gideon_interrupts_controls_vance"]
  day102_3_cora_frames_missy["day102_3_cora_frames_missy"] -->|"jump"| day102_3_gideon_interrupts_controls_vance["day102_3_gideon_interrupts_controls_vance"]
  day102_3_gideon_interrupts_controls_vance["day102_3_gideon_interrupts_controls_vance"] -->|"jump"| day102_4_night["day102_4_night"]
  day102_4_night["day102_4_night"] -->|"jump"| day102_4_cora_writes_a_chapter["day102_4_cora_writes_a_chapter"]
  day102_4_night["day102_4_night"] -->|"jump"| day102_4_cora_sneaks_a_feel["day102_4_cora_sneaks_a_feel"]
  day102_4_cora_writes_a_chapter["day102_4_cora_writes_a_chapter"] -->|"jump"| day103_morning["day103_morning"]
  day102_4_cora_sneaks_a_feel["day102_4_cora_sneaks_a_feel"] -->|"jump"| day103_morning["day103_morning"]
  day103["day103"] -->|"jump"| day103_morning["day103_morning"]
  day103_morning["day103_morning"] -->|"jump"| game_over_deadline_1["game_over_deadline_1"]
  day103_morning["day103_morning"] -->|"jump"| day103_1_servants_corridor["day103_1_servants_corridor"]
  day103_1_servants_corridor["day103_1_servants_corridor"] -->|"jump"| day103_1_corridor_insp_chain["day103_1_corridor_insp_chain"]
  day103_1_servants_corridor["day103_1_servants_corridor"] -->|"jump"| day103_1_corridor_corr_chain["day103_1_corridor_corr_chain"]
  day103_1_corridor_insp_chain["day103_1_corridor_insp_chain"] -->|"jump"| day103_afternoon["day103_afternoon"]
  day103_1_corridor_corr_chain["day103_1_corridor_corr_chain"] -->|"jump"| day103_afternoon["day103_afternoon"]
  day103_afternoon["day103_afternoon"] -->|"jump"| day103_2_suite_gideon_tea["day103_2_suite_gideon_tea"]
  day103_2_suite_gideon_tea["day103_2_suite_gideon_tea"] -->|"jump"| day103_2_suite_cora_vs_gideon["day103_2_suite_cora_vs_gideon"]
  day103_2_suite_cora_vs_gideon["day103_2_suite_cora_vs_gideon"] -->|"jump"| day103_2_cora_vs_gideon_insp["day103_2_cora_vs_gideon_insp"]
  day103_2_suite_cora_vs_gideon["day103_2_suite_cora_vs_gideon"] -->|"jump"| day103_2_cora_vs_gideon_corr["day103_2_cora_vs_gideon_corr"]
  day103_2_suite_cora_vs_gideon["day103_2_suite_cora_vs_gideon"] -->|"jump"| day103_2_cora_vs_gideon_ghost["day103_2_cora_vs_gideon_ghost"]
  day103_2_cora_vs_gideon_insp["day103_2_cora_vs_gideon_insp"] -->|"jump"| day103_2_suite_gideon_beat["day103_2_suite_gideon_beat"]
  day103_2_cora_vs_gideon_corr["day103_2_cora_vs_gideon_corr"] -->|"jump"| day103_2_suite_gideon_beat["day103_2_suite_gideon_beat"]
  day103_2_cora_vs_gideon_ghost["day103_2_cora_vs_gideon_ghost"] -->|"jump"| day103_2_suite_gideon_beat["day103_2_suite_gideon_beat"]
  day103_2_suite_gideon_beat["day103_2_suite_gideon_beat"] -->|"jump"| day103_3_bedroom_cora_frantic_writing_event["day103_3_bedroom_cora_frantic_writing_event"]
  day103_evening["day103_evening"] -->|"jump"| day103_3_bedroom_cora_frantic_writing_event["day103_3_bedroom_cora_frantic_writing_event"]
  day103_3_bedroom_cora_frantic_writing_event["day103_3_bedroom_cora_frantic_writing_event"] -->|"jump"| day103_3_frantic_write["day103_3_frantic_write"]
  day103_3_bedroom_cora_frantic_writing_event["day103_3_bedroom_cora_frantic_writing_event"] -->|"jump"| day103_3_prepare_mask["day103_3_prepare_mask"]
  day103_3_bedroom_cora_frantic_writing_event["day103_3_bedroom_cora_frantic_writing_event"] -->|"jump"| day103_3_indulge_words["day103_3_indulge_words"]
  day103_3_frantic_write["day103_3_frantic_write"] -->|"jump"| day103_4_room_stern_suspicion["day103_4_room_stern_suspicion"]
  day103_3_prepare_mask["day103_3_prepare_mask"] -->|"jump"| day103_4_room_stern_suspicion["day103_4_room_stern_suspicion"]
  day103_3_indulge_words["day103_3_indulge_words"] -->|"jump"| day103_4_room_stern_suspicion["day103_4_room_stern_suspicion"]
  day103_4_room_stern_suspicion["day103_4_room_stern_suspicion"] -->|"jump"| day103_2_suite_night_tea["day103_2_suite_night_tea"]
  day103_night["day103_night"] -->|"jump"| day103_2_suite_night_tea["day103_2_suite_night_tea"]
  day103_2_suite_night_tea["day103_2_suite_night_tea"] -->|"jump"| day103_2_night_defy_gideon["day103_2_night_defy_gideon"]
  day103_2_suite_night_tea["day103_2_suite_night_tea"] -->|"jump"| day103_2_night_bargain_gideon["day103_2_night_bargain_gideon"]
  day103_2_suite_night_tea["day103_2_suite_night_tea"] -->|"jump"| day103_2_night_surrender_gideon["day103_2_night_surrender_gideon"]
  day103_2_night_defy_gideon["day103_2_night_defy_gideon"] -->|"jump"| day103_3_bedroom_final_write["day103_3_bedroom_final_write"]
  day103_2_night_bargain_gideon["day103_2_night_bargain_gideon"] -->|"jump"| day103_3_bedroom_final_write["day103_3_bedroom_final_write"]
  day103_2_night_surrender_gideon["day103_2_night_surrender_gideon"] -->|"jump"| day103_3_bedroom_final_write["day103_3_bedroom_final_write"]
  day103_3_bedroom_final_write["day103_3_bedroom_final_write"] -->|"jump"| day104_1_false_dawn_suite_window["day104_1_false_dawn_suite_window"]
  day104["day104"] -->|"jump"| day104_morning["day104_morning"]
  day104_morning["day104_morning"] -->|"jump"| day104_1_false_dawn_suite_window["day104_1_false_dawn_suite_window"]
  day104_1_false_dawn_suite_window["day104_1_false_dawn_suite_window"] -->|"jump"| day104_1_lockbox_evidence["day104_1_lockbox_evidence"]
  day104_1_lockbox_evidence["day104_1_lockbox_evidence"] -->|"jump"| day104_2_return_early["day104_2_return_early"]
  day104_2_return_early["day104_2_return_early"] -->|"jump"| day104_2_escape_fireplace["day104_2_escape_fireplace"]
  day104_2_return_early["day104_2_return_early"] -->|"jump"| day104_2_escape_bold_lie["day104_2_escape_bold_lie"]
  day104_2_return_early["day104_2_return_early"] -->|"jump"| day104_2_escape_missy_cover["day104_2_escape_missy_cover"]
  day104_2_escape_fireplace["day104_2_escape_fireplace"] -->|"jump"| day104_evening["day104_evening"]
  day104_2_escape_bold_lie["day104_2_escape_bold_lie"] -->|"jump"| day104_evening["day104_evening"]
  day104_2_escape_missy_cover["day104_2_escape_missy_cover"] -->|"jump"| day104_evening["day104_evening"]
  day104_evening["day104_evening"] -->|"jump"| day104_3_stern_pressure["day104_3_stern_pressure"]
  day104_3_stern_pressure["day104_3_stern_pressure"] -->|"jump"| day104_4_twilight_ledger_false_dawn["day104_4_twilight_ledger_false_dawn"]
  day104_4_twilight_ledger_false_dawn["day104_4_twilight_ledger_false_dawn"] -->|"jump"| day104_4_atonement["day104_4_atonement"]
  day104_4_twilight_ledger_false_dawn["day104_4_twilight_ledger_false_dawn"] -->|"jump"| day104_4_twilight_ledger_false_dawn["day104_4_twilight_ledger_false_dawn"]
  day104_4_twilight_ledger_false_dawn["day104_4_twilight_ledger_false_dawn"] -->|"jump"| day104_night["day104_night"]
  day104_4_twilight_ledger_false_dawn["day104_4_twilight_ledger_false_dawn"] -->|"jump"| day104_4_missy_repair["day104_4_missy_repair"]
  day104_4_atonement["day104_4_atonement"] -->|"jump"| day104_6_false_dawn_ending["day104_6_false_dawn_ending"]
  day104_4_missy_repair["day104_4_missy_repair"] -->|"jump"| day104_6_false_dawn_ending["day104_6_false_dawn_ending"]
  day104_night["day104_night"] -->|"jump"| day104_5_triumphant_chapter["day104_5_triumphant_chapter"]
  day104_5_triumphant_chapter["day104_5_triumphant_chapter"] -->|"jump"| day104_6_false_dawn_ending["day104_6_false_dawn_ending"]
  day104_6_false_dawn_ending["day104_6_false_dawn_ending"] -->|"jump"| game_over_deadline_2["game_over_deadline_2"]
  day104_6_false_dawn_ending["day104_6_false_dawn_ending"] -->|"jump"| day105_1_monster_reemerges["day105_1_monster_reemerges"]
  day105_1_monster_reemerges["day105_1_monster_reemerges"] -->|"jump"| day105_2_the_summons["day105_2_the_summons"]
  day105_2_the_summons["day105_2_the_summons"] -->|"jump"| day105_3_leverage_collapses["day105_3_leverage_collapses"]
  day105_3_leverage_collapses["day105_3_leverage_collapses"] -->|"jump"| day105_4_why_did_you_do_it["day105_4_why_did_you_do_it"]
  day105_4_why_did_you_do_it["day105_4_why_did_you_do_it"] -->|"jump"| day105_4_motivation_observer["day105_4_motivation_observer"]
  day105_4_why_did_you_do_it["day105_4_why_did_you_do_it"] -->|"jump"| day105_4_motivation_predator["day105_4_motivation_predator"]
  day105_4_why_did_you_do_it["day105_4_why_did_you_do_it"] -->|"jump"| day105_4_motivation_prey["day105_4_motivation_prey"]
  day105_4_why_did_you_do_it["day105_4_why_did_you_do_it"] -->|"jump"| day105_4_motivation_ghost["day105_4_motivation_ghost"]
  day105_4_motivation_observer["day105_4_motivation_observer"] -->|"jump"| day105_5_gideon_marks_cora["day105_5_gideon_marks_cora"]
  day105_4_motivation_predator["day105_4_motivation_predator"] -->|"jump"| day105_5_gideon_marks_cora["day105_5_gideon_marks_cora"]
  day105_4_motivation_prey["day105_4_motivation_prey"] -->|"jump"| day105_5_gideon_marks_cora["day105_5_gideon_marks_cora"]
  day105_4_motivation_ghost["day105_4_motivation_ghost"] -->|"jump"| day105_5_gideon_marks_cora["day105_5_gideon_marks_cora"]
  day105_5_gideon_marks_cora["day105_5_gideon_marks_cora"] -->|"jump"| day105_6_manuscript_reckoning["day105_6_manuscript_reckoning"]
  day105_6_manuscript_reckoning["day105_6_manuscript_reckoning"] -->|"jump"| bad_ending_rejection["bad_ending_rejection"]
  day105_6_manuscript_reckoning["day105_6_manuscript_reckoning"] -->|"jump"| day105_7_release_one_ending["day105_7_release_one_ending"]
  test_day2_writing_harness["test_day2_writing_harness"] -->|"jump"| test_day2_render_book1_day2_predator["test_day2_render_book1_day2_predator"]
  test_day2_writing_harness["test_day2_writing_harness"] -->|"jump"| test_day2_render_book1_day2_ghost["test_day2_render_book1_day2_ghost"]
  test_day2_writing_harness["test_day2_writing_harness"] -->|"jump"| test_day2_render_book1_day2_prey["test_day2_render_book1_day2_prey"]
  test_day2_writing_harness["test_day2_writing_harness"] -->|"jump"| test_book1_render_day1_chapter["test_book1_render_day1_chapter"]
  test_day2_writing_harness["test_day2_writing_harness"] -->|"jump"| test_book1_render_day3_chapter["test_book1_render_day3_chapter"]
  test_day2_writing_harness["test_day2_writing_harness"] -->|"jump"| test_book1_render_day4_triumphant_chapter["test_book1_render_day4_triumphant_chapter"]
  test_day2_writing_harness["test_day2_writing_harness"] -->|"jump"| test_book1_render_day5_reckoning_chapter["test_book1_render_day5_reckoning_chapter"]
  watch_suspicion["watch_suspicion"] -->|"jump"| game_over_dismissed["game_over_dismissed"]
  advance_after_confrontation["advance_after_confrontation"] -->|"jump_expression"| dynamic__target_2_["dynamic:_target[2]"]
