#!/usr/bin/env python3
"""Generate balance_profiles_non_canon.rpy from effect_profiles.yaml."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from balance_resolver import DEFAULT_PROFILES_PATH, load_profiles  # noqa: E402

DEFAULT_NON_PROD_OUTPUT = (
    ROOT / "main-game" / "non-prod-game" / "game" / "shared" / "balance_profiles_non_canon.rpy"
)
DEFAULT_PROD_OUTPUT = ROOT / "main-game" / "prod-game" / "game" / "balance_profiles.rpy"
DEFAULT_OUTPUTS = (DEFAULT_NON_PROD_OUTPUT, DEFAULT_PROD_OUTPUT)

RESOLVER_FUNCTIONS = '''
    SCALE_PRECISION = 6

    def _is_number(value):
        return isinstance(value, (int, float)) and not isinstance(value, bool)

    def _clean_scale(value):
        return round(float(value), SCALE_PRECISION)

    def _resolve_balance_amount(stat_key, intensity_key, scale_modifier=1.0):
        if intensity_key is None:
            return 0

        if stat_key not in BALANCE_STAT_UNITS:
            raise ValueError("Unknown balance stat unit: {}".format(stat_key))

        scale_modifier = _clean_scale(scale_modifier)
        base_unit = BALANCE_STAT_UNITS[stat_key]

        if _is_number(intensity_key):
            base_multiplier = _clean_scale(intensity_key)
        else:
            if intensity_key not in BALANCE_INTENSITIES:
                raise ValueError("Unknown balance intensity constant: {}".format(intensity_key))
            base_multiplier = _clean_scale(BALANCE_INTENSITIES[intensity_key])

        return int(round(base_unit * base_multiplier * scale_modifier))

    def _resolve_intensity_scale_modifier(intensity_override):
        if intensity_override is None or intensity_override == "standard":
            return 1.0

        if _is_number(intensity_override):
            return _clean_scale(intensity_override)

        if intensity_override not in BALANCE_INTENSITIES:
            raise ValueError("Unknown balance intensity override: {}".format(intensity_override))

        standard = BALANCE_INTENSITIES["standard"]
        if standard == 0:
            raise ValueError("BALANCE_INTENSITIES['standard'] cannot be zero.")

        return _clean_scale(BALANCE_INTENSITIES[intensity_override] / standard)

    def resolve_balanced_effect(profile, intensity_override=None, witness=None, base_witness=False):
        if profile not in BALANCE_PROFILES:
            raise ValueError("Unknown balance profile: {}".format(profile))

        if witness is not None and witness not in BALANCE_VALID_WITNESSES:
            raise ValueError(
                "Unknown witness '{}'. Must be one of: {}".format(
                    witness,
                    ", ".join(BALANCE_VALID_WITNESSES),
                )
            )

        spec = BALANCE_PROFILES[profile]
        kwargs = {}
        scale_mod = _resolve_intensity_scale_modifier(intensity_override)

        if "insp" in spec:
            kwargs["insp"] = _resolve_balance_amount("insp", spec["insp"], scale_mod)

        if "corr" in spec:
            kwargs["corr"] = _resolve_balance_amount("corr", spec["corr"], scale_mod)

        if "witness_susp" in spec:
            if witness is None:
                raise ValueError("Profile '{}' requires a named witness parameter.".format(profile))

            amount = _resolve_balance_amount("susp", spec["witness_susp"], scale_mod)
            key = "{}_base".format(witness) if base_witness else "{}_susp".format(witness)
            kwargs[key] = amount

        return kwargs
'''


def render_rpy(config: dict[str, object], source_rel: str) -> str:
    profile_entries = []
    for name, spec in config["profiles"].items():
        inner = ", ".join(
            f'"{k}": "{v}"' if isinstance(v, str) else f'"{k}": {v}' for k, v in spec.items()
        )
        profile_entries.append(f'        "{name}": {{{inner}}},')

    witnesses = ", ".join(f'"{w}"' for w in config["valid_witnesses"])
    stat_lines = ", ".join(f'"{k}": {v}' for k, v in config["stat_units"].items())
    intensity_lines = ", ".join(f'"{k}": {v}' for k, v in config["intensities"].items())

    return f"""# Generated by scripts/generate_balance_profiles_rpy.py — do not edit by hand.
# Source: {source_rel}

init -1 python in balance_resolver:

    BALANCE_STAT_UNITS = {{{stat_lines}}}

    BALANCE_INTENSITIES = {{{intensity_lines}}}

    BALANCE_VALID_WITNESSES = ({witnesses})

    BALANCE_PROFILES = {{
{chr(10).join(profile_entries)}
    }}
{RESOLVER_FUNCTIONS}
"""


def build_rpy(yaml_path: Path) -> str:
    config = load_profiles(yaml_path)
    try:
        source_rel = yaml_path.relative_to(ROOT).as_posix()
    except ValueError:
        source_rel = yaml_path.as_posix()
    return render_rpy(config, source_rel)


def write_outputs(content: str, outputs: tuple[Path, ...]) -> None:
    for out_path in outputs:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8")
        print(f"Wrote {out_path.relative_to(ROOT).as_posix()}")


def check_outputs(content: str, outputs: tuple[Path, ...]) -> int:
    normalized = content.replace("\r\n", "\n")
    failures = 0
    for out_path in outputs:
        if not out_path.exists():
            print(f"Missing generated file: {out_path}", file=sys.stderr)
            failures += 1
            continue
        existing = out_path.read_text(encoding="utf-8").replace("\r\n", "\n")
        if existing != normalized:
            print(f"Generated file is out of sync: {out_path}", file=sys.stderr)
            failures += 1
        else:
            print(f"OK — {out_path.relative_to(ROOT).as_posix()} matches YAML source")
    if failures:
        print("Run: py scripts/generate_balance_profiles_rpy.py", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate balance profile runtime tables from effect_profiles.yaml."
    )
    parser.add_argument(
        "--yaml",
        type=Path,
        default=DEFAULT_PROFILES_PATH,
        help="Path to effect_profiles.yaml",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Single output .rpy path (default: write non-prod + prod targets)",
    )
    parser.add_argument(
        "--prod-only",
        action="store_true",
        help="Write only main-game/prod-game/game/balance_profiles.rpy",
    )
    parser.add_argument(
        "--non-prod-only",
        action="store_true",
        help="Write only balance_profiles_non_canon.rpy",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if output file(s) differ from generated content",
    )
    args = parser.parse_args()

    if args.prod_only and args.non_prod_only:
        print("Choose at most one of --prod-only or --non-prod-only.", file=sys.stderr)
        return 2

    yaml_path = args.yaml if args.yaml.is_absolute() else ROOT / args.yaml
    if args.out is not None:
        out_path = args.out if args.out.is_absolute() else ROOT / args.out
        outputs = (out_path,)
    elif args.prod_only:
        outputs = (DEFAULT_PROD_OUTPUT,)
    elif args.non_prod_only:
        outputs = (DEFAULT_NON_PROD_OUTPUT,)
    else:
        outputs = DEFAULT_OUTPUTS

    content = build_rpy(yaml_path)

    if args.check:
        return check_outputs(content, outputs)

    write_outputs(content, outputs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
