#!/usr/bin/env python3
"""Generate balance_profiles_non_canon.rpy from effect_profiles.yaml."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from balance_resolver import DEFAULT_PROFILES_PATH, load_profiles  # noqa: E402
from balance_catalogue import parse_balanced_effect_line  # noqa: E402

DEFAULT_NON_PROD_OUTPUT = (
    ROOT / "main-game" / "non-prod-game" / "game" / "shared" / "balance_profiles_non_canon.rpy"
)
DEFAULT_PROD_OUTPUT = ROOT / "main-game" / "prod-game" / "game" / "balance_profiles.rpy"
DEFAULT_OUTPUTS = (DEFAULT_NON_PROD_OUTPUT, DEFAULT_PROD_OUTPUT)


def render_rpy(config: dict[str, object], source_rel: str) -> str:
    profile_entries = []
    for name, spec in config["profiles"].items():
        if spec.get("active", False):
            deltas_str = []
            for intensity, deltas in spec.get("deltas", {}).items():
                deltas_str.append(f'            "{intensity}": {repr(deltas)},')
            inner = f'"active": True,\n        "deltas": {{\n{chr(10).join(deltas_str)}\n        }}'
        else:
            inner = f'"active": False,\n        "migration_hint": "{spec.get("migration_hint", "")}"'
        profile_entries.append(f'        "{name}": {{\n            {inner}\n        }},')

    witnesses = ", ".join(f'"{w}"' for w in config["valid_witnesses"])
    active_intensities = ", ".join(f'"{i}"' for i in config["active_intensities"])
    allowed_story_intensities = ", ".join(
        f'"{i}"' for i in config.get("migration_mode", {}).get("allowed_story_intensities", ())
    )

    return f"""# Generated by scripts/generate_balance_profiles_rpy.py — do not edit by hand.
# Source: {source_rel}

init -1 python in balance_resolver:

    BALANCE_SCHEMA_VERSION = {config.get("schema_version", 2)}
    BALANCE_ACTIVE_INTENSITIES = ({active_intensities})
    BALANCE_MIGRATION_ALLOWED_STORY_INTENSITIES = ({allowed_story_intensities})
    BALANCE_VALID_WITNESSES = ({witnesses})

    BALANCE_PROFILES = {{
{chr(10).join(profile_entries)}
    }}

    def resolve_balanced_effect(profile, intensity_override="standard", witness=None, base_witness=False):
        if profile not in BALANCE_PROFILES:
            raise ValueError("Unknown balance profile: {{}}".format(profile))

        prof_data = BALANCE_PROFILES[profile]
        if not prof_data.get("active", False):
            raise ValueError("Profile '{{}}' is inactive.".format(profile))

        intensity = intensity_override if intensity_override is not None else "standard"

        if isinstance(intensity, (int, float)) and not isinstance(intensity, bool):
            raise ValueError("Numeric intensity override not supported in schema v2: {{}}".format(intensity))

        if intensity not in BALANCE_ACTIVE_INTENSITIES:
            raise ValueError("Inactive or unknown intensity: {{}}".format(intensity))

        if base_witness:
            raise ValueError("base_witness=True is not allowed for active profiles during this migration pass.")

        deltas = prof_data.get("deltas", {{}}).get(intensity, {{}})

        kwargs = {{}}
        if deltas.get("insp", 0) != 0:
            kwargs["insp"] = deltas["insp"]
        if deltas.get("corr", 0) != 0:
            kwargs["corr"] = deltas["corr"]

        witness_susp = deltas.get("witness_susp", 0)
        if witness_susp != 0:
            if witness is None:
                raise ValueError("Profile '{{}}' requires a named witness parameter.".format(profile))
            if witness not in BALANCE_VALID_WITNESSES:
                raise ValueError("Unknown witness '{{}}'. Must be one of: {{}}".format(witness, ", ".join(BALANCE_VALID_WITNESSES)))
            key = "{{}}_base".format(witness) if base_witness else "{{}}_susp".format(witness)
            kwargs[key] = witness_susp

        return kwargs
"""


def scan_prod_for_legacy_references(prod_dir: Path) -> list[str]:
    violations = []
    inactive_profiles = {"safe", "obedient", "submissive", "defiant", "reckless", "predatory", "self_protective"}
    inactive_intensities = {"trace", "severe"}

    for rpy_path in prod_dir.rglob("*.rpy"):
        if rpy_path.name == "balance_profiles.rpy":
            continue
        try:
            content = rpy_path.read_text(encoding="utf-8")
        except Exception:
            continue

        for idx, line in enumerate(content.splitlines(), start=1):
            if "apply_balanced_effect" not in line:
                continue
            effect = parse_balanced_effect_line(line)
            if not effect:
                continue

            if effect.profile in inactive_profiles:
                violations.append(
                    f"{rpy_path.relative_to(ROOT).as_posix()}:{idx} uses inactive profile '{effect.profile}'"
                )
            if effect.intensity in inactive_intensities:
                violations.append(
                    f"{rpy_path.relative_to(ROOT).as_posix()}:{idx} uses inactive intensity '{effect.intensity}'"
                )
            elif isinstance(effect.intensity, (int, float)):
                violations.append(
                    f"{rpy_path.relative_to(ROOT).as_posix()}:{idx} uses numeric intensity override '{effect.intensity}'"
                )
    return violations


def build_rpy(yaml_path: Path) -> str:
    config = load_profiles(yaml_path)
    try:
        source_rel = yaml_path.relative_to(ROOT).as_posix()
    except ValueError:
        source_rel = yaml_path.as_posix()
    return render_rpy(config, source_rel)


def write_outputs(content: str, outputs: tuple[Path, ...]) -> None:
    for out_path in outputs:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8")
        print(f"Wrote {out_path.relative_to(ROOT).as_posix()}")


def check_outputs(content: str, outputs: tuple[Path, ...]) -> int:
    normalized = content.replace("\r\n", "\n")
    failures = 0
    for out_path in outputs:
        if not out_path.exists():
            print(f"Missing generated file: {out_path}", file=sys.stderr)
            failures += 1
            continue
        existing = out_path.read_text(encoding="utf-8").replace("\r\n", "\n")
        if existing != normalized:
            print(f"Generated file is out of sync: {out_path}", file=sys.stderr)
            failures += 1
        else:
            print(f"OK — {out_path.relative_to(ROOT).as_posix()} matches YAML source")
    if failures:
        print("Run: py scripts/generate_balance_profiles_rpy.py", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate balance profile runtime tables from effect_profiles.yaml."
    )
    parser.add_argument(
        "--yaml",
        type=Path,
        default=DEFAULT_PROFILES_PATH,
        help="Path to effect_profiles.yaml",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Single output .rpy path (default: write non-prod + prod targets)",
    )
    parser.add_argument(
        "--prod-only",
        action="store_true",
        help="Write only main-game/prod-game/game/balance_profiles.rpy",
    )
    parser.add_argument(
        "--non-prod-only",
        action="store_true",
        help="Write only balance_profiles_non_canon.rpy",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if output file(s) differ from generated content",
    )
    args = parser.parse_args()

    if args.prod_only and args.non_prod_only:
        print("Choose at most one of --prod-only or --non-prod-only.", file=sys.stderr)
        return 2

    yaml_path = args.yaml if args.yaml.is_absolute() else ROOT / args.yaml
    if args.out is not None:
        out_path = args.out if args.out.is_absolute() else ROOT / args.out
        outputs = (out_path,)
    elif args.prod_only:
        outputs = (DEFAULT_PROD_OUTPUT,)
    elif args.non_prod_only:
        outputs = (DEFAULT_NON_PROD_OUTPUT,)
    else:
        outputs = DEFAULT_OUTPUTS

    if DEFAULT_PROD_OUTPUT in outputs:
        prod_dir = ROOT / "main-game" / "prod-game"
        violations = scan_prod_for_legacy_references(prod_dir)
        if violations:
            print("Cannot write prod balance_profiles.rpy from schema v2.", file=sys.stderr)
            print("Prod contains inactive balance profile calls or invalid intensities:", file=sys.stderr)
            for v in violations[:10]:
                print(f"  {v}", file=sys.stderr)
            if len(violations) > 10:
                print(f"  ... and {len(violations) - 10} more", file=sys.stderr)
            print("Run with --non-prod-only for migration mode, or migrate prod first.", file=sys.stderr)
            return 3

    content = build_rpy(yaml_path)

    if args.check:
        return check_outputs(content, outputs)

    write_outputs(content, outputs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
